### ISSUE TITLE
Make weather plugin do hourly forecasts

### ISSUE THREAD

**Issue by jonheese-wti** [jonheese/moonbeam-bot#15]

**Comment by jonheese** [comment]
Unfortunately, Weatherbit charges $40/month for access to the Hourly weather forecast API :(

Groundwork was laid in https://github.com/jonheese/moonbeam-bot/commit/4a219d86c184e7913fa78b158f61e7f8a5db0534 anyway

**Comment by jonheese** [comment]
Reopening this so we can try to make this work using the DarkSky API instead of Weatherbit

**Comment by jonheese** [comment]
This is done in https://github.com/jonheese/moonbeam-bot/commit/8878eeb4d1a957184769318f71b3f5d6cf245e71
